# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b937a21b3728c9c46856ffc4c12ed6d3c68a15dafe356ef08b457bbb37feeeada7bfabddf72d4dc0d8f5b215699d364117b97af624aca8aabda67c84d89ed35
  admin_pass: 321321321

test:
  secret_key_base: 27697b20f9e269ad60595ea37f7e2ac6aaa92c7e785b9a2323532221ec4a63529be1a4d1a40de71584d67c70aa9d5dbfc173109b6428881af6c7eca30be2c4cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
